export function createHtml(script: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Churnkey Flow Explorer</title>
<style>
:root{color-scheme:light dark;--bg:#f8f9fb;--card:#fff;--ink:#19232c;--muted:#62707c;--line:#e2e7ec;--accent:#176e56;--soft:#e9f5ef;font-family:var(--font-sans,Inter,system-ui,sans-serif)}
@media(prefers-color-scheme:dark){:root{--bg:#181b20;--card:#22262c;--ink:#eef2f5;--muted:#aab6c0;--line:#3a4149;--accent:#7ddbb6;--soft:#183c30}}
:root[data-theme=light]{color-scheme:light;--bg:#f8f9fb;--card:#fff;--ink:#19232c;--muted:#62707c;--line:#e2e7ec;--accent:#176e56;--soft:#e9f5ef}
:root[data-theme=dark]{color-scheme:dark;--bg:#181b20;--card:#22262c;--ink:#eef2f5;--muted:#aab6c0;--line:#3a4149;--accent:#7ddbb6;--soft:#183c30}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink)}main{max-width:1280px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:26px}.brand{font-size:12px;letter-spacing:.13em;font-weight:800;color:var(--accent)}h1{font-size:28px;letter-spacing:-.04em;margin:8px 0}h2{font-size:20px;letter-spacing:-.02em;margin:0 0 12px}p{line-height:1.5}.muted,small{color:var(--muted)}button,input,select{font:inherit;color:inherit}button{cursor:pointer;border:1px solid var(--line);border-radius:9px;background:var(--card);padding:10px 14px;font-weight:600}button:hover{border-color:var(--accent)}button:disabled{cursor:default;opacity:.5}.primary{background:var(--accent);color:var(--card);border:0}input,select{background:var(--card);border:1px solid var(--line);border-radius:9px;padding:10px;width:100%}label{display:block;font-size:12px;color:var(--muted);margin-bottom:6px}.layout{display:grid;grid-template-columns:330px minmax(0,1fr);gap:22px}.panel{border:1px solid var(--line);background:var(--card);border-radius:14px;padding:22px;min-width:0}.flow-list{display:grid;gap:10px;margin-top:16px}.flow{display:block;width:100%;text-align:left;padding:16px}.flow strong{display:block;margin-bottom:10px;overflow-wrap:anywhere}.flow.selected{border-color:var(--accent);background:var(--soft)}.badge{display:inline-block;border:1px solid var(--line);font-size:11px;padding:4px 7px;border-radius:6px;color:var(--muted)}.active{color:var(--accent);background:var(--soft)}.detail-head{display:flex;justify-content:space-between;align-items:start;gap:12px}.date-range{max-width:170px}.metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:24px 0}.metric{border:1px solid var(--line);border-radius:10px;padding:16px}.number{font-size:26px;letter-spacing:-.03em;font-weight:750;display:block;margin-bottom:5px}.steps{display:grid;gap:10px;margin:18px 0 24px}.step{display:flex;gap:12px;border:1px solid var(--line);border-radius:9px;padding:13px}.step-num{border-radius:7px;background:var(--soft);color:var(--accent);padding:6px 10px;align-self:start;font-size:12px;font-weight:700}.step strong{font-size:14px}.step p{font-size:13px;margin:5px 0 0;overflow-wrap:anywhere}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:22px}.note{font-size:12px;margin:16px 0 0}.warning{border-left:3px solid #cf952b;padding:10px 14px;background:var(--bg);font-size:13px;margin:14px 0}.empty{padding:30px 0;color:var(--muted)}#error{color:#b84838;overflow-wrap:anywhere}#workspace{font-size:13px}.demo-banner{background:#fff1c8;color:#704a00;padding:10px 18px;font-size:12px;font-weight:600;text-align:center}.break{overflow-wrap:anywhere}
@media(max-width:760px){main{padding:18px}.layout{grid-template-columns:1fr}.flow-list{grid-template-columns:repeat(2,minmax(0,1fr))}.detail-head{flex-wrap:wrap}.metrics{gap:6px}.metric{padding:10px}.number{font-size:21px}header{align-items:start}.panel{padding:16px}}@media(max-width:390px){.flow-list,.metrics{grid-template-columns:1fr}header{flex-wrap:wrap}}
</style></head><body><main><header><div><div class="brand">CHURNKEY</div><h1>Flow Explorer</h1><div id="workspace" class="muted">Connecting to your workspace…</div></div><button id="refresh" disabled>Refresh flows</button></header><p id="error" role="alert" hidden></p><div class="layout"><aside class="panel"><h2>Your cancel flows</h2><label for="search">Find a flow</label><input id="search" type="search" placeholder="Search flows…"><div id="flows" class="flow-list"></div><p class="note muted">Configuration is shared across live and test modes.</p></aside><section id="detail" class="panel" aria-live="polite"><div class="empty">Choose a flow to explore its published version.</div></section></div></main><script type="module">${script.replaceAll('</script', '<\\/script')}</script></body></html>`
}
